# print card information
gp-info

# load everything in one go
gp-load --reload \
	build/javacard/openjavacard-lib-ber.cap \
	build/javacard/openjavacard-lib-string.cap \
	build/javacard/openjavacard-lib-fortuna.cap \
	build/javacard/openjavacard-lib-password.cap \
	build/javacard/openjavacard-lib-debug.cap \
	build/javacard/openjavacard-lib-ctlv.cap \
	build/javacard/openjavacard-app-demo.cap

# install demo applet
gp-install --reinstall --package D276000177100210010001 --module D27600017710021001000101 --aid D27600017710011001

# list result
gp-list
